### ISSUE TITLE
undeclared identifier

### ISSUE THREAD

**Issue by Mutharasi** [FMJ-Software/ieCpp#5]
While using Image Eye source code with my project created in visual studio 2015, and building the project it shows undeclared identifier error. 
The error is "**Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'ieDotsPerMeter': undeclared identifier	myProject	c:\users\acer\documents\visual studio 2015\projects\myproject\myproject\ief_bmp.cpp	861	

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'ieDotsPerInch': undeclared identifier	myProject	c:\users\acer\documents\visual studio 2015\projects\myproject\myproject\ief_xmp.cpp	712**	"
What may be the reason?
Thanks in advance

**Comment by FMJ-Software** [comment]
Hi,

Be sure to check out the latest ieC++. These were recently named from DotsPerInch to PixelsPerInch.

Best regards, 

/ Markus


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: Mutharasi <notifications@github.com> </div><div>Date:2016/02/02  12:17  (GMT+01:00) </div><div>To: FMJ-Software/ieCpp <ieCpp@noreply.github.com> </div><div>Subject: [ieCpp] undeclared identifier (#5) </div><div>
</div>While using Image Eye source code with my project created in visual studio 2015, and building the project it shows undeclared identifier error 
The error is "**Severity Code Description Project File Line Suppression State
Error C2065 'ieDotsPerMeter': undeclared identifier myProject c:\users\acer\documents\visual studio 2015\projects\myproject\myproject\ief_bmpcpp 861

Severity Code Description Project File Line Suppression State
Error C2065 'ieDotsPerInch': undeclared identifier myProject c:\users\acer\documents\visual studio 2015\projects\myproject\myproject\ief_xmpcpp 712** "
What may be the reason?
Thanks in advance

**Comment by Mutharasi** [comment]
Hi,

Thank you so much. That problem is solved. But now I have the following errors:
"**LNK2019	unresolved external symbol "void __cdecl ie_BGR2BGRA(struct ieBGRA *,struct ieBGR const *,unsigned long)" (?ie_BGR2BGRA@@YAXPAUieBGRA@@PBUieBGR@@K@Z) referenced in function "public: virtual unsigned long __thiscall ie_bmp_Reader::ReadImageX(class ieImage *,bool,class ieProgress *,bool volatile *)" (?ReadImageX@ie_bmp_Reader@@UAEKPAVieImage@@_NPAVieProgress@@PC_N@Z)	myProject	C:\Users\Acer\Documents\Visual Studio 2015\Projects\myProject\myProject\ief_bmp.obj	1	

LNK2001	unresolved external symbol "public: virtual unsigned long __thiscall ieFileReaderX::ReadMeta(bool volatile *)" (?ReadMeta@ieFileReaderX@@UAEKPC_N@Z)	myProject	C:\Users\Acer\Documents\Visual Studio 2015\Projects\myProject\myProject\ief_bmp.obj	1	

LNK1120	15 unresolved externals	myProject	C:\Users\Acer\Documents\Visual Studio 2015\Projects\myProject\Debug\myProject.exe	1**	"

Can you please help me?
Is there any problem in using the library files in my project?

Thanks,

**Comment by FMJ-Software** [comment]
Have you included ieColorX2BGRA.cpp and ieFileFormats.cpp in your project?
Do the sample applications compile?

**Comment by Mutharasi** [comment]
Yes included those files in my project. Getting error in sample applications also.

**Comment by Mutharasi** [comment]
Can you tell me how to include .h and .cpp files in project? So that I can cross check it with my project and clarify it?

**Comment by FMJ-Software** [comment]
I just downloaded a fresh copy of the files and opened the "ieC++.sln" sample project and tested it.
It compiles fine with Visual Studio2015 (update 1).
So does a fresh copy of the Image Eye project.
Take a look at how things are set up in the sample project.
I'm sorry I can't be of much more help.

Best regards,
/ Markus

**Comment by Mutharasi** [comment]
I too did the same. I am using visual studio 2015 (Update 1). Downloaded the fresh copy and opened the "ieC++.sln" sample project. I tested it. But I am getting error.

**Comment by FMJ-Software** [comment]
That's strange. If it can't link with ie_BGR2BGRA and ieCOlorX2BGRA.cpp is included in the project (that's where the function is implemented) and you haven't changed any project settings (e.g. calling convention), then I don't know.

Do you get the same error if you compile for 64-bit as if you compile for 32-bit?
Do you get the same error if you compile for Debug target as if you compile for release target?

**Comment by Mutharasi** [comment]
I didn't change any project settings. I opened the recent project downloaded and tried to build it. Yes for both 64-bit, 32-bit and Debug, Release.

**Comment by Mutharasi** [comment]
After including the paths it is working fine. Thanks .. 

And when adding the ieC++/Src file and including the header file to the project while adding ieAddModule(png) it is showing linker errors. 

Error 1 error LNK2019: unresolved external symbol "void cdecl ie_iptc_Init(class ieFileFormatTableManager &)" (?ie_iptc_Init@@YAXAAVieFileFormatTableManager@@@Z) referenced in function "int cdecl InitInstance(struct HINSTANCE__ *,int)" (?InitInstance@@YAHPAUHINSTANCE__@@H@Z) C:\Users\welcome\documents\visual studio 2013\Projects\Win32Project2\Win32Project2\Win32Project2.obj Win32Project2

 Error 2 error LNK2001: unresolved external symbol "class ieFileFormatTableManager ieFormatTable" (?ieFormatTable@@3VieFileFormatTableManager@@A) C:\Users\welcome\documents\visual studio 2013\Projects\Win32Project2\Win32Project2\Win32Project2.obj Win32Project2

What I did is 
1) Included ieC++/Src  to the additional including directories and  "ieC++.h".
2) added ieAddModule(png) to the code and getting the above error .. 

Do I need to do anything at build ? Please explain 

Thanks.

**Comment by FMJ-Software** [comment]
Ah, I see, yes of course you need to add an include path to the header files to your project settings.
The png module shouldn't be dependent on iptc I think. Did you add tiff or psd as well?
Anyhow, just include ief_iptc.cpp and ieFileFormats.cpp to your project to give the linker what it wants.

**Comment by Mutharasi** [comment]
Thanks for the Reply. Tried with tiff and psd the same link error is displaying. 

And when tried with adding ief_iptc.cpp and ieFileFormats.cpp (including headerfiles) then some link error displayed. 

After adding all files also, I am getting errors. 
Error	9	error C4703: potentially uninitialized local pointer variable 'pCLUT' used	
Error	11	error C4703: potentially uninitialized local pointer variable 'pbUncompTile' used
Error	12	error C4703: potentially uninitialized local pointer variable 'pbCompTileEnd' used
Error	10	error C4703: potentially uninitialized local pointer variable 'clut' used	
Error	7	error C2838: 'Bilinear' : illegal qualified name in member declaration	
Error	2	error C2664: 'iePImage ieImage::Create(iePixelFormat,ieWH,bool,bool,DWORD,DWORD)' : cannot convert argument 2 from 'ieDist' to 'ieWH'	
Error	3	error C2660: 'ie_DitherwL2L' : function does not take 6 arguments	
Error	1	error C2660: 'ie_DitherwBGRA2BGRA' : function does not take 6 arguments	
Error	8	error C2065: 'Bilinear' : undeclared identifier	
Error	4	error C1083: Cannot open include file: 'mdCharConv.h': No such file or directory	
Error	5	error C1083: Cannot open include file: '..\..\jpeg-9b\jinclude.h': No such file or directory	
Error	6	error C1083: Cannot open include file: '../../fif/isDeco32.h': No such file or directory	


I have included the md file folder path.

And adding "ieAddModule(tiff)" in EyeView sample project also showing error. 
It will be helpful in the way if we add the path in the project and nothing more to do. 

If I am creating any mistake please ignore. And if possible please provide simple sample project which can display image by giving file path like EyeView in simple way. 

Thanks.

**Comment by FMJ-Software** [comment]
I'm sorry but I can not reproduce the errors that you get.

There is already two sample projects included!
